=== raquelmvz/Schemas/Personas/personas.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="personas" type="tipoPersonas" />

    <xs:complexType name="tipoPersonas">
        <xs:sequence>
            <xs:element name="persona" type="tipoPersona" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoPersona">
        <xs:sequence>
            <xs:element name="nombre" type="tipoNombre"/>
            <xs:element name="nacimiento" type="tipoNacimiento"/>
            <xs:element name="direcciones" type="tipoDirecciones"/>
            <xs:choice>
                <xs:element name="varon" type="tipoVacio" />
                <xs:element name="mujer" type="tipoVacio" />
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoNacimiento">
        <xs:attribute name="dia" type="tipoDia"/>
        <xs:attribute name="mes" type="tipoMes"/>
        <xs:attribute name="anyo" type="tipoAnyo"/>
    </xs:complexType>

    <xs:simpleType name="tipoDia">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoMes">
        <xs:restriction base="xs:string">
           <xs:enumeration value="Enero"/>
           <xs:enumeration value="Febrero"/>
           <xs:enumeration value="Marzo"/>
           <xs:enumeration value="Abril"/>
           <xs:enumeration value="Mayo"/>
           <xs:enumeration value="Junio"/>
           <xs:enumeration value="Julio"/>
           <xs:enumeration value="Agosto"/>
           <xs:enumeration value="Septiembre"/>
           <xs:enumeration value="Octubre"/>
           <xs:enumeration value="Noviembre"/>
           <xs:enumeration value="Diciembre"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoAnyo">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1900"/>
            <xs:maxInclusive value="2011"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="tipoDirecciones">
        <xs:sequence>
            <xs:element name="direccion" type="tipoDireccion" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoDireccion">
        <xs:sequence>
            <xs:element name="calle" type="tipoNombre"/>
            <xs:element name="poblacion" type="tipoNombre"/>
            <xs:element name="provincia" type="tipoNombre"/>
            <xs:element name="cpostal" type="tipoCodPostal"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="tipoNombre">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoCodPostal">
        <xs:restriction base="xs:positiveInteger">
            <xs:totalDigits value="5"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="tipoVacio" />

</xs:schema>

=== raquelmvz/Schemas/Personas/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="personas.xsd">

	<persona>

		<nombre>Juan Pardo</nombre>

		<nacimiento dia="10" mes="Abril" anyo="1982"/>

		<direcciones>
			<direccion>
				<calle>Caoba, 1</calle>
				<poblacion>Madrid</poblacion>
				<provincia>Madrid</provincia>
				<cpostal>28005</cpostal>
			</direccion>

		</direcciones>

		<varon/>

	</persona>


	<persona>

		<nombre>Maria Lopez</nombre>

		<nacimiento dia="10" mes="Abril" anyo="1982"/>

		<direcciones>
			<direccion>
				<calle>Roncato,1</calle>
				<poblacion>Illescas</poblacion>
				<provincia>Toledo</provincia>
				<cpostal>45200</cpostal>
			</direccion>

			<direccion>
				<calle>Paseo de la Esperanza 15, 1ÂºA</calle>
				<poblacion>Madrid</poblacion>
				<provincia>Madrid</provincia>
				<cpostal>28005</cpostal>
			</direccion>

		</direcciones>

		<mujer/>

	</persona>

</personas>
